# Project: TugasBesarDDP
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o penjualantiket.o bioskop.o paymentkonser.o paymentbioskop.o hotel.o history.o
LINKOBJ  = main.o penjualantiket.o bioskop.o paymentkonser.o paymentbioskop.o hotel.o history.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = TugasBesarDDP.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

penjualantiket.o: penjualantiket.c
	$(CC) -c penjualantiket.c -o penjualantiket.o $(CFLAGS)

bioskop.o: bioskop.c
	$(CC) -c bioskop.c -o bioskop.o $(CFLAGS)

paymentkonser.o: paymentkonser.c
	$(CC) -c paymentkonser.c -o paymentkonser.o $(CFLAGS)

paymentbioskop.o: paymentbioskop.c
	$(CC) -c paymentbioskop.c -o paymentbioskop.o $(CFLAGS)

hotel.o: hotel.c
	$(CC) -c hotel.c -o hotel.o $(CFLAGS)

history.o: history.c
	$(CC) -c history.c -o history.o $(CFLAGS)
